export const MODULE_NAME = '9GAG';
export const DOMAIN = '9gag.com';

export function capture(response, source_platform_url, source_url) {
    let domain = source_platform_url.split("/")[2].toLowerCase().replace(/^www\./, '');

    if (!["9gag.com"].includes(domain)) {
        return [];
    }


    /**
     * Some data is embedded in the page rather than loaded asynchronously.
     * This here extracts it!
     */
    let embedded_sigil_start = /(window\._config = JSON.parse\()/mg;
    let embedded_sigil_end = /(\);<\/script>)/mg;
    let data;
    if(embedded_sigil_start.test(response)) {
        response = response.split(embedded_sigil_start)[2];
        if(!embedded_sigil_end.test(response)) {
            return [];
        }
        try {
            const embedded_json = response.split(embedded_sigil_end)[0];
            response = JSON.parse(embedded_json);
        } catch (e) {
            return [];
        }
    }

    try {
        data = JSON.parse(response);
    } catch (e) {
        return [];
    }

    if(!data || typeof data["data"] !== 'object' || !("data" in data) || !("posts" in data["data"])) {
        return [];
    }

    return data["data"]["posts"];
}

// === auto-generated by 4cat map_item sync — BLOCK REPLACED AUTOMATICALLY ===
// (regenerated from datasources/ninegag/search_9gag.py)
export function map_item(post) {
    // Convert Unix timestamp (seconds) to Date object
    const postTimestampSec = post.creationTs;
    const postTimestamp = new Date(postTimestampSec * 1000);

    // Select the highest‑resolution image that is not a video
    const images = Object.values(post.images ?? {});
    const imageCandidates = images.filter(v => !('hasAudio' in v));
    imageCandidates.sort((a, b) => (b.width * b.height) - (a.width * a.height));
    const image = imageCandidates[0] ?? {};

    // Select the highest‑resolution video (if any) and pick the best URL format
    const videoCandidates = images.filter(v => ('hasAudio' in v));
    videoCandidates.sort((a, b) => (b.width * b.height) - (a.width * a.height));
    let videoUrl = "";
    if (videoCandidates.length) {
        const vid = videoCandidates[0];
        if (vid.av1Url) videoUrl = vid.av1Url;
        else if (vid.h265Url) videoUrl = vid.h265Url;
        else if (vid.vp9Url) videoUrl = vid.vp9Url;
        else if (vid.vp8Url) videoUrl = vid.vp8Url;
    }

    // Handle anonymous posts – they appear as the user "9GAGGER"
    if (!post.creator) {
        post.creator = {
            username: "9GAGGER",
            fullName: "",
            emojiStatus: "",
            isVerifiedAccount: ""
        };
    }

    return new MappedItem({
        collected_from_url: normalize_url_encoding(post.__import_meta?.source_platform_url ?? ""),
        id: post.id,
        url: post.url,
        subject: post.title,
        body: post.description,
        timestamp: formatUtcTimestamp(postTimestampSec),
        author: post.creator?.username ?? "",
        author_name: post.creator?.fullName ?? "",
        author_status: post.creator?.emojiStatus ?? "",
        author_verified: post.creator?.isVerifiedAccount ? "yes" : "no",
        type: post.type,
        image_url: image.url ?? "",
        video_url: videoUrl,
        is_nsfw: post.nsfw === 0 ? "no" : "yes",
        is_promoted: post.promoted === 0 ? "no" : "yes",
        is_vote_masked: post.isVoteMasked === 0 ? "no" : "yes",
        is_anonymous: !post.isAnonymous ? "no" : "yes",
        source_domain: post.sourceDomain,
        source_url: post.sourceUrl,
        upvotes: post.upVoteCount,
        downvotes: post.downVoteCount,
        score: (post.upVoteCount ?? 0) - (post.downVoteCount ?? 0),
        comments: post.commentsCount,
        tags: (post.tags ?? []).map(t => t.key).join(","),
        tags_annotated: (post.annotationTags ?? []).join(","),
        unix_timestamp: postTimestampSec
    });
}
// === end auto-generated ===
