export const MODULE_NAME = 'Gab';
export const DOMAIN = 'gab.com';

// Function to remove HTML tags using a DOM Parser
function removeHtmlTagsUsingDOMParser(htmlString) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlString, 'text/html');
    return doc.body.textContent || "";
}

export function capture(response, source_platform_url, source_url) {
    let domain = source_platform_url.split("/")[2].toLowerCase().replace(/^www\./, '');

    // Check if the domain is gab.com and the source_url corresponds to the expected endpoints
    if (!["gab.com"].includes(domain)) {
        return [];
    }

    let data;
    let items = [];

    try {
        data = JSON.parse(response);
    } catch (SyntaxError) {
        return [];
    }


    /// capture posts in explore, groups, or from a user's profile
    if ((source_url.indexOf('explore?') >= 0 || source_url.indexOf('timelines/group/') >= 0 || source_url.indexOf('accounts/')) && data.s && Array.isArray(data.s)) {
        for (let post of data.s) {
            post["id"] = post.i;
            post["c"] = removeHtmlTagsUsingDOMParser(post.c);
            post["link_info"] = null;
            post["image_info"] = null;
            for (let author of data.a) {
                if (author.i == post.ai) {
                    if (author["nt"]) {
                        author["nt"] = removeHtmlTagsUsingDOMParser(author.nt);
                    }
                    post["author_info"] = author;
                }
            }
            if (post.pci) {
                for (let link of data.pc) {
                    if (post.pci == link.id) {
                        post["link_info"] = link;
                    }
                }
            }
            if (post.mai) {
                let images = [];
                for (let post_image of post.mai) {
                    for (let image of data.ma) {
                        if (post_image == image.i) {
                            images.push(image);
                        }
                    }
                }
                post["image_info"] = images;
            }
            items.push(post);
        }
    }

    /// capture posts in search
    if (source_url.indexOf('search?') >= 0 && data.statuses && Array.isArray(data.statuses)) {
        for (let post of data.statuses) {
            post["id"] = post.id;
            post["c"] = removeHtmlTagsUsingDOMParser(post.content);
            items.push(post);
        }
    }
    return items;
}

// === auto-generated by 4cat map_item sync — BLOCK REPLACED AUTOMATICALLY ===
// (regenerated from datasources/gab/search_gab.py)
export function map_item(item) {
    const unknownData = [];

    const postId = item['i'] ?? item['id'];
    const metadata = item['__import_meta'] ?? {};

    let collectedAt;
    if (metadata['timestamp_collected'] != null) {
        const ts = metadata['timestamp_collected'] / 1000;
        collectedAt = formatUtcTimestamp(ts);
    } else {
        collectedAt = new MissingMappedField('Unknown');
    }

    const reactions = item['rc'] ?? item['reactions_counts'];
    let reactionCount;
    if (typeof reactions === 'number') {
        reactionCount = reactions;
    } else {
        reactionCount = Object.values(reactions ?? {}).reduce((sum, val) => sum + (val ?? 0), 0);
    }

    const group = item['g'] ?? item['group'] ?? null;
    const author = item['author_info'] ?? item['account'] ?? null;
    const mentions = item['m'] ?? item['mentions'] ?? [];
    const tags = item['tg'] ?? item['tags'] ?? [];
    const card = item['card'] ?? item['link'] ?? null;
    const mediaItems = item['image_info'] ?? item['media_attachments'] ?? [];

    const imageUrls = [];
    const videoUrls = [];

    for (const media of mediaItems) {
        const type = media['t'] ?? media['type'];
        if (type === 'image') {
            const url = media['u'] ?? media['url'];
            if (url == null) {
                unknownData.push(`Media missing URL: ${url}`);
            } else {
                imageUrls.push(url);
            }
        } else if (type === 'video') {
            const url = media['smp4'] ?? media['source_mp4'];
            if (url == null) {
                unknownData.push(`Media missing URL: ${url}`);
            } else {
                videoUrls.push(url);
            }
        } else {
            unknownData.push(`Unknown media type: ${JSON.stringify(media)}`);
        }
    }

    const createdAtRaw = item['ca'] ?? item['created_at'];
    const postDate = new Date(createdAtRaw);
    const postTimeStr = formatUtcTimestamp(postDate.getTime() / 1000);

    const mappedItem = {
        collected_at: collectedAt,
        collected_from_url: normalize_url_encoding(metadata['source_platform_url'] ?? ''),
        id: postId,
        created_at: postTimeStr,
        body: item['c'] ?? item['content'],
        url: item['ul'] ?? item['url'],
        reaction_count: reactionCount,
        favourites_count: item['fbc'] ?? item['favourites_count'],
        replies_count: item['rc'] ?? item['replies_count'],
        reblogs_count: item['rbc'] ?? item['reblogs_count'],
        mentions: mentions.map(m => m['username']).join(','),
        tags: tags.map(t => t['name']).join(','),

        group_id: group ? group['id'] ?? null : null,
        group_title: group ? group['title'] ?? null : null,
        group_description: group ? group['description'] ?? null : null,
        group_member_count: group ? group['member_count'] ?? null : null,
        group_is_private: group ? group['is_private'] ?? null : null,
        group_url: group ? group['url'] ?? null : null,
        group_created_at: group ? group['created_at'] ?? null : null,

        account_id: author ? (author['i'] ?? author['id']) : null,
        account_username: author ? (author['un'] ?? author['username']) : null,
        account_account: author ? (author['ac'] ?? author['acct']) : null,
        account_display_name: author ? (author['dn'] ?? author['display_name']) : null,
        account_note: author ? (author['nt'] ?? author['note']) : null,

        link_id: card ? card['id'] ?? null : null,
        link_url: card ? card['url'] ?? null : null,
        link_title: card ? card['title'] ?? null : null,
        link_description: card ? card['description'] ?? null : null,
        link_type: card ? card['type'] ?? null : null,
        link_image: card ? card['image'] ?? null : null,

        image_urls: imageUrls.join(','),
        video_urls: videoUrls.join(','),

        thread_id: item['i'] ?? item['conversation_id'],
        timestamp: postTimeStr
    };

    if (unknownData.length) {
        return new MappedItem(mappedItem, {message: unknownData.join('')});
    }
    return new MappedItem(mappedItem);
}
// === end auto-generated ===
