export const MODULE_NAME = 'Imgur';
export const DOMAIN = 'imgur.com';

export function capture(response, source_platform_url, source_url) {
    let domain = source_platform_url.split("/")[2].toLowerCase().replace(/^www\./, '');

    if (!["imgur.com"].includes(domain)) {
        return [];
    }

    let data;
    try {
        data = JSON.parse(response);
    } catch (SyntaxError) {
        return [];
    }


    if(typeof data !== 'object' || !("posts" in data) || typeof data["posts"] !== 'object') {
        if(typeof data === 'object') {
            // heuristic to determine if objects are actually posts
            let post_objects = data.filter(function(item) {
                return typeof item === 'object' && 'id' in item && 'account_id' in item && 'point_count' in item;
            });
            if(post_objects.length === data.length) {
                return post_objects;
            }
        }
        return [];
    }

    return data["posts"];
}

// === auto-generated by 4cat map_item sync — BLOCK REPLACED AUTOMATICALLY ===
// (regenerated from datasources/imgur/search_imgur.py)
export function map_item(item) {
    // Parse created_at timestamp (ISO 8601) to Unix seconds
    const createdAt = item.created_at;
    if (!createdAt) {
        throw new MapItemException('Missing created_at field');
    }
    const unix_timestamp = Math.floor(Date.parse(createdAt) / 1000);
    const timestamp = formatUtcTimestamp(unix_timestamp);

    const collected_from_url = normalize_url_encoding(item.__import_meta?.source_platform_url ?? "");

    return new MappedItem({
        collected_from_url,
        id: item.id,
        subject: item.title,
        body: item.description,
        timestamp,
        author: item.account_id,
        type: item.cover?.type,
        media_url: item.cover?.url,
        post_url: item.url,
        album_media: item.image_count,
        is_ad: item.is_ad ? "yes" : "no",
        is_album: item.is_album ? "yes" : "no",
        is_mature: item.is_mature ? "yes" : "no",
        is_viral: item.in_most_viral ? "yes" : "no",
        views: item.view_count,
        upvotes: item.upvote_count,
        downvotes: item.downvote_count,
        score: item.point_count,
        comments: item.comment_count,
        favourites: item.favorite_count,
        virality_score: item.virality,
        unix_timestamp,
    });
}
// === end auto-generated ===
