export const MODULE_NAME = 'Pinterest';
export const DOMAIN = 'pinterest.com';

export function capture(response, source_platform_url, source_url) {
    let domain = source_platform_url.split("/")[2].toLowerCase().replace(/^www\./, '');
    if (!domain.endsWith('pinterest.com')) {
        return [];
    }

    /**
     * Some data is embedded in the page rather than loaded asynchronously.
     * This here extracts it!
     */
    if(!response) {
        return [];
    }

    let pins = [];
    let data = [];

    try {
        if(response.indexOf('<!DOCTYPE html>') >= 0) {
            throw new Error();
        }
        // when dealing with JSON, just parse that JSON and process it
        const json_data = JSON.parse(response);
        data.push(json_data);
    } catch (e) {
        // data is not JSON, so it's probably HTML
        // HTML has data embedded in <script> tags
        // store these for processing
        const code_regex = RegExp(/<script data-relay-response="true" type="application\/json">([^<]+)<\/script>/g);

        for (const code_bit of response.matchAll(code_regex)) {
            try {
                // use he to decode from HTML entities (the way the data is embedded)
                data.push(JSON.parse(he.decode(code_bit[1].trim())));
            } catch (e) {
            }
        }

        // now extract some stuff from the HTML by making a DOM tree and pulling from it
        // this is far less complete than the json objects, but good enough that it might
        // be useful for a researcher
        if(response.indexOf('<!DOCTYPE html>') >= 0) {
            const dummyDocument = new DOMParser().parseFromString(response, 'text/html');
            const embedded_pins = dummyDocument.querySelectorAll("article[data-test-id='bestPin']");
            for(const embedded_pin of embedded_pins) {
                const mapped_pin = {
                    'id': embedded_pin.querySelector('a').getAttribute('href').replace(/\/$/, '').split('/').pop().split('-').pop(),
                    'tags': Array.from(embedded_pin.querySelectorAll('div[data-test-id="vase-tag"]')).map(x => { return x.querySelector('a').innerText }),
                    'title': embedded_pin.querySelector('h2') ? embedded_pin.querySelector('h2').innerText : '',
                    'body': embedded_pin.querySelector('h3') ? embedded_pin.querySelector('h3').innerText : '',
                    'pins': Array.from(embedded_pin.querySelectorAll('div')).pop().innerText,
                    'image': embedded_pin.querySelector('img').getAttribute('src'),
                    '_zs-origin': 'html'
                };
                pins.push(mapped_pin);
            }
        }


    }

    for(const pin of traverse_data(data, function (item, property) {

        if (
            // post page recommendations: https://www.pinterest.com/pin/507921664242278249/
            (item.hasOwnProperty('__isNode') && item['__isNode'] === 'Pin')
            // ideas page: https://www.pinterest.com/ideas/2024-summer-olympics/920026959546/
            // board page: https://www.pinterest.com/nahidessa/spiritual-groups/
            // user page: https://www.pinterest.com/walmart/
            // search results: https://www.pinterest.com/search/pins/?q=Aesthetic%20vibes
            || (item.hasOwnProperty('type') && item['type'] === 'pin')
            // front page: https://www.pinterest.com/ideas/
            // main explore page
            || (item.hasOwnProperty('__typename') && item['__typename'] === 'Pin' && property === 'node')
        ) {
            if ((!item.hasOwnProperty('images') && !item.hasOwnProperty('imageSpec_orig')) || !item.hasOwnProperty('pinner')) {
                // incomplete post... sometimes happens on 'find similar pins' page
                return;
            }
            if (item.hasOwnProperty('entityId')) {
                item['id'] = item['entityId'];
            }
            item['_zs-origin'] = 'json';
            return item;
        }
    })) {
        pins.push(pin);
    }

    return pins;
}

// === auto-generated by 4cat map_item sync — BLOCK REPLACED AUTOMATICALLY ===
// (regenerated from datasources/pinterest/search_pinterest.py)
export function map_item(item) {
    function map_item_from_json(post) {
        // Parse timestamp, handling missing or malformed values
        let timestampStr = post['created_at'] ?? post['createdAt'];
        let unix_timestamp;
        let str_timestamp;
        if (timestampStr) {
            let date = new Date(timestampStr);
            if (!isNaN(date)) {
                unix_timestamp = Math.floor(date.getTime() / 1000);
                str_timestamp = formatUtcTimestamp(unix_timestamp);
            } else {
                unix_timestamp = new MissingMappedField("");
                str_timestamp = new MissingMappedField("");
            }
        } else {
            unix_timestamp = new MissingMappedField("");
            str_timestamp = new MissingMappedField("");
        }

        let post_id = post['entityId'] ?? post['id'];

        let image_url;
        if (post['imageSpec_orig']) {
            image_url = post['imageSpec_orig']['url'];
        } else if (post['images']?.orig?.url) {
            image_url = post['images']['orig']['url'];
        } else {
            image_url = post['images']?.url;
        }

        return new MappedItem({
            collected_from_url: normalize_url_encoding(post['__import_meta']?.source_platform_url ?? ""),
            id: post_id,
            thread_id: post_id,
            author: post['pinner']?.username,
            author_fullname: post['pinner']?.fullName ?? post['pinner']?.full_name ?? "",
            author_original: post['nativeCreator'] ? post['nativeCreator'].username : post['pinner']?.username,
            body: (post['description'] ?? "").trim(),
            subject: (post['title'] ?? "").trim(),
            ai_description: post['auto_alt_text'] ?? "",
            pinner_original: post['originPinner'] ? post['originPinner'].fullName : "",
            pinner_via: post['viaPinner'] ? post['viaPinner'].fullName : "",
            board: post['board']?.name,
            board_pins: post['board']?.pinCount ?? post['board']?.pin_count ?? null,
            board_url: post['board']?.url ? `https://www.pinterest.com${post['board'].url}` : null,
            timestamp: str_timestamp,
            idea_tags: post['pinJoin'] ? (post['pinJoin']['visualAnnotation'] ?? []).join(",") : "",
            url: `https://www.pinterest.com/pin/${post_id}`,
            is_video: (post['isVideo'] ?? post['videos']) ? "yes" : "no",
            image_url: image_url,
            dominant_colour: post['dominantColor'] ?? post['dominant_color'] ?? null,
            unix_timestamp: unix_timestamp
        });
    }

    function map_item_from_html(post) {
        return new MappedItem({
            collected_from_url: normalize_url_encoding(post['__import_meta']?.source_platform_url ?? ""),
            id: parseInt(post['id'], 10),
            thread_id: parseInt(post['id'], 10),
            author: new MissingMappedField(""),
            author_fullname: new MissingMappedField(""),
            author_original: new MissingMappedField(""),
            body: (post['body'] ?? "").trim(),
            subject: (post['title'] ?? "").trim(),
            ai_description: new MissingMappedField(""),
            pinner_original: new MissingMappedField(""),
            pinner_via: new MissingMappedField(""),
            board: new MissingMappedField(""),
            board_pins: new MissingMappedField(""),
            board_url: new MissingMappedField(""),
            timestamp: new MissingMappedField(""),
            idea_tags: (post['tags'] ?? []).join(","),
            url: `https://www.pinterest.com/pin/${post['id']}`,
            is_video: new MissingMappedField(""),
            image_url: post['image'],
            dominant_colour: new MissingMappedField(""),
            unix_timestamp: new MissingMappedField("")
        });
    }

    if (item['_zs-origin'] === 'html') {
        return map_item_from_html(item);
    }
    return map_item_from_json(item);
}
// === end auto-generated ===
