export const MODULE_NAME = 'Threads';
export const DOMAIN = 'threads.com';
export const MODULE_ID = 'threads.net';

export function capture(response, source_platform_url, source_url) {
    let domain = source_platform_url.split("/")[2].toLowerCase().replace(/^www\./, '');

    if (!["threads.net", "threads.com"].includes(domain)) {
        return [];
    }

    let datas = [];
    try {
        // if it's JSON already, just parse it
        datas.push(JSON.parse(response));
    } catch {
        // data can be embedded in the HTML in these JavaScript statements
        // this is identical to Instagram (see instagram.js)

        let js_prefixes = [
            new RegExp(/\{"require":\[\["ScheduledServerJS","handle",null,\[\{"__bbox":\{"require":\[\["RelayPrefetchedStreamCache[^"]*","next",\[],/)
        ];

        let prefix;

        while (js_prefixes.length > 0) {
            prefix = js_prefixes.shift();

            // we go through the response line by line, because prefixes may
            // occur multiple times but always on a single line
            for (const line of response.split("\n")) {
                if (!prefix.test(line)) {
                    // prefix not found
                    continue;
                }

                let json_bit = line.split(prefix)[1].split('</script>')[0].trim();
                if (json_bit.endsWith(';')) {
                    json_bit = json_bit.substring(0, -1);
                }

                if (js_prefixes.length === 0) {
                    // last prefix has some special handling
                    // remove trailing stuff...
                    json_bit = json_bit.split(']]}}')[0];
                }

                json_bit = json_bit.split('],["CometResourceScheduler"')[0];


                try {
                    datas.push(JSON.parse(json_bit));
                } catch {
                    // fine, not JSON after all
                }
            }
        }

        if (datas.length === 0) {
            // console.log('no datas for ' + source_url);
            return [];
        }
    }

    console.log('have ' + datas.length + ' datas from ' + source_platform_url)

    return [...traverse_data(datas, function (item, property) {
        if (property === 'post' && item['pk'] && item['code']) {
            return item;
        }
    })]
}

// === auto-generated by 4cat map_item sync — BLOCK REPLACED AUTOMATICALLY ===
// (regenerated from datasources/threads/search_threads.py)
export function map_item(item) {
    const post = item;
    const timestampStr = post.taken_at != null ? formatUtcTimestamp(post.taken_at) : "";
    let imageUrls = [];
    let videoUrls = [];

    if (post.carousel_media && post.carousel_media.length) {
        for (const c of post.carousel_media) {
            if (c.image_versions2 && c.image_versions2.candidates && c.image_versions2.candidates.length) {
                const url = c.image_versions2.candidates[0].url;
                if (url) imageUrls.push(url);
            }
            if (c.video_versions && c.video_versions.length) {
                const vurl = c.video_versions[0].url;
                if (vurl) videoUrls.push(vurl);
            }
        }
    } else {
        if (post.image_versions2 && post.image_versions2.candidates && post.image_versions2.candidates.length) {
            const url = post.image_versions2.candidates[0].url;
            if (url) imageUrls.push(url);
        }
        if (post.video_versions && post.video_versions.length) {
            const vurl = post.video_versions[0].url;
            if (vurl) videoUrls.push(vurl);
        }
    }

    const audioUrl = post.audio && post.audio.audio_src ? post.audio.audio_src : "";

    let linkedUrl = "";
    let linkThumbnail = "";
    const linkPreview = post.text_post_app_info && post.text_post_app_info.link_preview_attachment;
    if (linkPreview) {
        linkedUrl = linkPreview.url || "";
        try {
            const parsed = new URL(linkedUrl);
            const uParam = parsed.searchParams.getAll('u');
            if (uParam.length) {
                linkedUrl = uParam[0];
                linkThumbnail = linkPreview.image_url ?? "";
            } else {
                linkThumbnail = linkedUrl;
            }
        } catch (e) {
            linkThumbnail = linkedUrl;
        }
    }

    const hashtags = post.caption && post.caption.text
        ? [...post.caption.text.matchAll(/#([^\\s!@#$%ˆ&*()_+{}:"|<>?\\[\\];',.\\/`~']+)/g)].map(m => m[1]).join(',')
        : "";

    return new MappedItem({
        collected_from_url: normalize_url_encoding(post.__import_meta?.source_platform_url ?? ""),
        id: post.code,
        thread_id: post.code,
        url: `https://www.threads.com/@${post.user?.username ?? ""}/post/${post.code}`,
        body: post.caption?.text ?? "",
        timestamp: timestampStr,
        author: post.user?.username ?? "",
        author_is_verified: post.user?.is_verified ? "yes" : "no",
        author_avatar: post.user?.profile_pic_url ?? null,
        image_url: imageUrls.join(","),
        video_url: videoUrls.join(","),
        audio_url: audioUrl,
        link_url: linkedUrl,
        link_thumbnail_url: linkThumbnail ?? "",
        is_paid_partnership: post.is_paid_partnership ? "yes" : "no",
        likes: post.like_count,
        reposts: post.text_post_app_info?.repost_count ?? 0,
        replies: post.text_post_app_info?.direct_reply_count ?? 0,
        quotes: post.text_post_app_info?.quote_count ?? 0,
        hashtags: hashtags,
        unix_timestamp: post.taken_at != null ? Math.floor(post.taken_at) : null
    });
}
// === end auto-generated ===
