
export const MODULE_NAME = 'TikTok (posts)';
export const DOMAIN = 'tiktok.com';

export function capture(response, source_platform_url, source_url) {
    let domain = source_platform_url.split("/")[2].toLowerCase().replace(/^www\./, '');
    if (domain !== 'tiktok.com') {
        return [];
    }

    /**
     * Some data is embedded in the page rather than loaded asynchronously.
     * This here extracts it!
     */
    let embedded_sigil_start = /(window\['SIGI_STATE']\s*=\s*|<script id="SIGI_STATE" type="application\/json">)/mg;
    let embedded_sigil_end = /(;\s*window\['SIGI_RETRY']\s*=\s*|<\/script>)/mg;
    let data;
    let from_embed = false;
    if(embedded_sigil_start.test(response)) {
        response = response.split(embedded_sigil_start)[2];
        if(!embedded_sigil_end.test(response)) {
            return [];
        }
        response = response.split(embedded_sigil_end)[0];
        from_embed = true;
    }

    // NEW: detect JSON embedded in HTML via <script id="__UNIVERSAL_DATA_FOR_REHYDRATION__" type="application/json">
    if (!from_embed && typeof response === 'string' && response.indexOf('<script') >= 0) {
        const udrMatch = response.match(/<script[^>]+id="__UNIVERSAL_DATA_FOR_REHYDRATION__"[^>]*type=["']application\/json["'][^>]*>([\s\S]*?)<\/script>/i);
        if (udrMatch && udrMatch[1]) {
            try {
                const ud = JSON.parse(udrMatch[1]);
                const scope = ud && ud.__DEFAULT_SCOPE__;
                const updatedItems = scope && scope["webapp.updated-items"];
                if (Array.isArray(updatedItems)) {
                    // Return items from the new payload, excluding live items
                    return updatedItems.filter(x => !x?.liveRoomInfo);
                }
                const singleItem = scope && scope["webapp.video-detail"] && scope["webapp.video-detail"].itemInfo && scope["webapp.video-detail"].itemInfo.itemStruct;
                if (singleItem) {
                    return [singleItem];
                }
            } catch (e) {
                // fall through to other strategies
            }
        }
    }

    if(!response) {
        return [];
    }

    try {
        data = JSON.parse(response);
    } catch (SyntaxError) {
        return [];
    }

    // TikTok preloads some data (for example on hover over a link)
    // https://www.tiktok.com/api/preload/item_list/ returns itemList array with full items that may not be reloaded if the user visits the link
    const from_preload = (typeof source_url === 'string') && (source_url.indexOf('/api/preload/') >= 0);
    if (from_preload) {
        // We could updated add an attribute to the items to indicate they are from preload, but we should encourage a full reload anyway
        // So we just ignore these items for now
        return [];
    }

    if("ItemModule" in data) {
        let r = Object.values(data["ItemModule"]);
        return r.filter(x => !x.hasOwnProperty('liveRoomInfo'));
    } else if ("itemList" in data) {
        return data["itemList"].filter(x => !x.hasOwnProperty('liveRoomInfo'));
    } else if ("item_list" in data) {
        return data["item_list"].filter(x => !x.hasOwnProperty('liveRoomInfo'));
    } else if ("data" in data) {
        // search results "top results" (i.e. not the video tab)
        let r = Object.values(data["data"]);
        let useable_items = [];
        if(r.length === 0) {
            return [];
        }
        let items = r.filter(x => x.hasOwnProperty('item') && x.hasOwnProperty('type')).map(x => x["item"]);
        let known_fields = ["id", "desc", "createTime", "music"];
        let bad_fields = ["liveRoomInfo"]; // if these are present, skip the post, e.g. for live streams
        for(let i in items) {
            let item = items[i];
            let item_ok = true;
            for (let j in known_fields) {
                if (!item.hasOwnProperty(known_fields[j])) {
                    item_ok = false;
                }
            }
            for (let j in bad_fields) {
                if (item.hasOwnProperty(bad_fields[j])) {
                    item_ok = false;
                }
            }
            if(item_ok) {
                useable_items.push(item);
            }
        }
        return useable_items;
    } else {
        return [];
    }
}

// === auto-generated by 4cat map_item sync — DO NOT EDIT BY HAND ===
// (regenerated from datasources/tiktok/search_tiktok.py)
export function map_item(post) {
  // Zeeschuimer metadata
  const metadata = post.__import_meta || {};

  const challenges = Array.isArray(post.challenges)
    ? post.challenges.map(ch => ch.title).filter(Boolean)
    : [];

  const hashtags = Array.isArray(post.textExtra)
    ? post.textExtra
        .filter(e => e.hasOwnProperty('hashtagName') && e.hashtagName)
        .map(e => e.hashtagName)
    : [];

  const diversificationLabels = Array.isArray(post.diversificationLabels)
    ? post.diversificationLabels.join(',')
    : '';

  let user_nickname = '';
  let user_fullname = '';
  let user_thumbnail = '';

  if (post.author && typeof post.author === 'object') {
    user_nickname = post.author.uniqueId || '';
    user_fullname = post.author.nickname || '';
    user_thumbnail = post.author.avatarThumb || '';
  } else if (post.author) {
    user_nickname = post.author || '';
    user_fullname = post.nickname || '';
    user_thumbnail = '';
  }

  const thumbnailOptions = [];

  if (post.video && Array.isArray(post.video.shareCover)) {
    thumbnailOptions.push(...post.video.shareCover);
  }

  if (post.video && post.video.cover) {
    thumbnailOptions.push(post.video.cover);
  }

  const now = Math.floor(Date.now() / 1000);

  const validThumbnails = thumbnailOptions.filter(url => {
    try {
      const parsedUrl = new URL(url);
      const expires = parseInt(parsedUrl.searchParams.get('x-expires'), 10) || 0;
      return expires >= now;
    } catch (e) {
      return false;
    }
  });

  const thumbnail_url = validThumbnails.length ? validThumbnails[validThumbnails.length - 1] : '';

  return new MappedItem({
    collected_from_url: metadata.source_platform_url
      ? normalize_url_encoding(metadata.source_platform_url)
      : '',
    id: post.id || '',
    thread_id: post.id || '',
    author: user_nickname,
    author_full: user_fullname,
    author_followers: post.authorStats?.followerCount ?? '',
    author_likes: post.authorStats?.diggCount ?? '',
    author_videos: post.authorStats?.videoCount ?? '',
    author_avatar: user_thumbnail,
    body: post.desc || '',
    stickers: Array.isArray(post.stickersOnItem)
      ? post.stickersOnItem
          .map(s => (Array.isArray(s.stickerText) ? s.stickerText.join(' ') : ''))
          .filter(Boolean)
          .join('')
      : '',
    timestamp: post.createTime
      ? formatUtcTimestamp(parseInt(post.createTime, 10))
      : '',
    unix_timestamp: post.createTime ? parseInt(post.createTime, 10) : 0,
    is_duet:
      post.duetInfo && post.duetInfo.duetFromId && post.duetInfo.duetFromId !== '0'
        ? 'yes'
        : 'no',
    is_ad: post.isAd ? 'yes' : 'no',
    is_paid_partnership: post.adAuthorization ? 'yes' : 'no',
    is_sensitive: post.maskType === 3 ? 'yes' : 'no',
    is_photosensitive: post.maskType === 4 ? 'yes' : 'no',
    music_name: post.music?.title ?? '',
    music_id: post.music?.id ?? '',
    music_url: post.music?.playUrl ?? '',
    music_thumbnail: post.music?.coverLarge ?? '',
    music_author: post.music?.authorName ?? '',
    video_url: post.video?.downloadAddr ?? '',
    tiktok_url: `https://www.tiktok.com/@${user_nickname}/video/${post.id}`,
    thumbnail_url: thumbnail_url,
    likes: post.stats?.diggCount ?? '',
    comments: post.stats?.commentCount ?? '',
    shares: post.stats?.shareCount ?? '',
    plays: post.stats?.playCount ?? '',
    hashtags: hashtags.join(','),
    challenges: challenges.join(','),
    diversification_labels: diversificationLabels,
    location_created: post.locationCreated ?? '',
    effects: Array.isArray(post.effectStickers)
      ? post.effectStickers.map(e => e.name).join(',')
      : '',
    warning: Array.isArray(post.warnInfo)
      ? post.warnInfo.map(w => w.text).join(',')
      : '',
  });
}
// === end auto-generated ===
// === end auto-generated ===
