export const MODULE_NAME = 'TikTok (posts)';
export const DOMAIN = 'tiktok.com';

export function capture(response, source_platform_url, source_url) {
    let domain = source_platform_url.split("/")[2].toLowerCase().replace(/^www\./, '');
    if (domain !== 'tiktok.com') {
        return [];
    }

    /**
     * Some data is embedded in the page rather than loaded asynchronously.
     * This here extracts it!
     */
    let embedded_sigil_start = /(window\['SIGI_STATE']\s*=\s*|<script id="SIGI_STATE" type="application\/json">)/mg;
    let embedded_sigil_end = /(;\s*window\['SIGI_RETRY']\s*=\s*|<\/script>)/mg;
    let data;
    let from_embed = false;
    if(embedded_sigil_start.test(response)) {
        response = response.split(embedded_sigil_start)[2];
        if(!embedded_sigil_end.test(response)) {
            return [];
        }
        response = response.split(embedded_sigil_end)[0];
        from_embed = true;
    }

    // NEW: detect JSON embedded in HTML via <script id="__UNIVERSAL_DATA_FOR_REHYDRATION__" type="application/json">
    if (!from_embed && typeof response === 'string' && response.indexOf('<script') >= 0) {
        const udrMatch = response.match(/<script[^>]+id="__UNIVERSAL_DATA_FOR_REHYDRATION__"[^>]*type=["']application\/json["'][^>]*>([\s\S]*?)<\/script>/i);
        if (udrMatch && udrMatch[1]) {
            try {
                const ud = JSON.parse(udrMatch[1]);
                const scope = ud && ud.__DEFAULT_SCOPE__;
                const updatedItems = scope && scope["webapp.updated-items"];
                if (Array.isArray(updatedItems)) {
                    // Return items from the new payload, excluding live items
                    return updatedItems.filter(x => !x?.liveRoomInfo);
                }
                const singleItem = scope && scope["webapp.video-detail"] && scope["webapp.video-detail"].itemInfo && scope["webapp.video-detail"].itemInfo.itemStruct;
                if (singleItem) {
                    return [singleItem];
                }
            } catch (e) {
                // fall through to other strategies
            }
        }
    }

    if(!response) {
        return [];
    }

    try {
        data = JSON.parse(response);
    } catch (SyntaxError) {
        return [];
    }

    // TikTok preloads some data (for example on hover over a link)
    // https://www.tiktok.com/api/preload/item_list/ returns itemList array with full items that may not be reloaded if the user visits the link
    const from_preload = (typeof source_url === 'string') && (source_url.indexOf('/api/preload/') >= 0);
    if (from_preload) {
        // We could updated add an attribute to the items to indicate they are from preload, but we should encourage a full reload anyway
        // So we just ignore these items for now
        return [];
    }

    if("ItemModule" in data) {
        let r = Object.values(data["ItemModule"]);
        return r.filter(x => !x.hasOwnProperty('liveRoomInfo'));
    } else if ("itemList" in data) {
        return data["itemList"].filter(x => !x.hasOwnProperty('liveRoomInfo'));
    } else if ("item_list" in data) {
        return data["item_list"].filter(x => !x.hasOwnProperty('liveRoomInfo'));
    } else if ("data" in data) {
        // search results "top results" (i.e. not the video tab)
        let r = Object.values(data["data"]);
        let useable_items = [];
        if(r.length === 0) {
            return [];
        }
        let items = r.filter(x => x.hasOwnProperty('item') && x.hasOwnProperty('type')).map(x => x["item"]);
        let known_fields = ["id", "desc", "createTime", "music"];
        let bad_fields = ["liveRoomInfo"]; // if these are present, skip the post, e.g. for live streams
        for(let i in items) {
            let item = items[i];
            let item_ok = true;
            for (let j in known_fields) {
                if (!item.hasOwnProperty(known_fields[j])) {
                    item_ok = false;
                }
            }
            for (let j in bad_fields) {
                if (item.hasOwnProperty(bad_fields[j])) {
                    item_ok = false;
                }
            }
            if(item_ok) {
                useable_items.push(item);
            }
        }
        return useable_items;
    } else {
        return [];
    }
}

// === auto-generated by 4cat map_item sync — BLOCK REPLACED AUTOMATICALLY ===
// (regenerated from datasources/tiktok/search_tiktok.py)
function getValidThumbnail(options) {
    const now = Math.floor(Date.now() / 1000);
    const valid = options.filter(url => {
        try {
            const parsed = new URL(url);
            const expiresStr = parsed.searchParams.get('x-expires');
            const expires = expiresStr ? parseInt(expiresStr, 10) : now;
            return expires >= now;
        } catch (e) {
            return false;
        }
    });
    return valid.length ? valid.pop() : "";
}

export function map_item(item) {
    const post = item;
    // Zeeschuimer metadata
    const metadata = py_get(post, '__import_meta', {});

    // Challenges titles
    const challenges = (py_get(post, 'challenges', [])).map(ch => ch.title);

    // Hashtags extraction
    const hashtags = (py_get(post, 'textExtra', [])).filter(extra => 'hashtagName' in extra && extra.hashtagName).map(extra => extra.hashtagName);

    // Diversification labels
    const divLabels = py_get(post, 'diversificationLabels');
    const labels = Array.isArray(divLabels) ? divLabels.join(',') : '';

    // Author handling
    const authorField = py_get(post, 'author');
    let user_nickname = '';
    let user_fullname = '';
    let user_thumbnail = '';
    if (authorField && typeof authorField === 'object' && !Array.isArray(authorField)) {
        // from intercepted API response
        user_nickname = authorField.uniqueId ?? '';
        user_fullname = authorField.nickname ?? '';
        user_thumbnail = py_get(authorField, 'avatarThumb', '');
    } else if (authorField) {
        // from embedded JSON object
        user_nickname = authorField;
        user_fullname = py_get(post, 'nickname', '');
        user_thumbnail = '';
    }

    // Thumbnail selection
    const video = py_get(post, 'video', {});
    const thumbnailOptions = [];
    const shareCover = py_get(video, 'shareCover');
    if (Array.isArray(shareCover) && shareCover.length) {
        thumbnailOptions.push(shareCover[shareCover.length - 1]);
    }
    const cover = py_get(video, 'cover');
    if (cover) {
        thumbnailOptions.push(cover);
    }
    const thumbnail_url = getValidThumbnail(thumbnailOptions);

    // Stats and other fields
    const authorStats = py_get(post, 'authorStats', {});
    const stats = py_get(post, 'stats', {});
    const music = py_get(post, 'music', {});
    const effectStickers = py_get(post, 'effectStickers', []);
    const warnInfo = py_get(post, 'warnInfo', []);
    const stickersOnItem = py_get(post, 'stickersOnItem', []);

    const timestampSec = parseInt(post.createTime, 10);

    return new MappedItem({
        collected_from_url: metadata && py_get(metadata, 'source_platform_url') ? normalize_url_encoding(py_get(metadata, 'source_platform_url')) : "",
        id: post.id,
        thread_id: post.id,
        author: user_nickname,
        author_full: user_fullname,
        author_followers: py_get(authorStats, 'followerCount', ''),
        author_likes: py_get(authorStats, 'diggCount', ''),
        author_videos: py_get(authorStats, 'videoCount', ''),
        author_avatar: user_thumbnail,
        body: post.desc,
        stickers: stickersOnItem.map(s => (s.stickerText || []).join(' ')).join('\n'),
        timestamp: formatUtcTimestamp(timestampSec),
        unix_timestamp: timestampSec,
        is_image_post: py_get(post, 'imagePost') ? "yes" : "no",
        is_duet: (function(){ const duetInfo = py_get(post, 'duetInfo', {}); return duetInfo && duetInfo.duetFromId && duetInfo.duetFromId !== "0" ? "yes" : "no"; })(),
        is_ad: py_get(post, 'isAd', false) ? "yes" : "no",
        is_paid_partnership: py_get(post, 'adAuthorization') ? "yes" : "no",
        is_sensitive: py_get(post, 'maskType') === 3 ? "yes" : "no",
        is_photosensitive: py_get(post, 'maskType') === 4 ? "yes" : "no",
        music_name: music.title,
        music_id: music.id,
        music_url: py_get(music, 'playUrl', ''),
        music_thumbnail: py_get(music, 'coverLarge', ''),
        music_author: py_get(music, 'authorName', ''),
        video_url: py_get(video, 'downloadAddr', ''),
        tiktok_url: `https://www.tiktok.com/@${user_nickname}/video/${post.id}`,
        thumbnail_url: thumbnail_url,
        likes: py_get(stats, 'diggCount'),
        comments: py_get(stats, 'commentCount'),
        shares: py_get(stats, 'shareCount'),
        plays: py_get(stats, 'playCount'),
        hashtags: hashtags.join(','),
        challenges: challenges.join(','),
        diversification_labels: labels,
        location_created: py_get(post, 'locationCreated', ''),
        effects: effectStickers.map(e => e.name).join(','),
        warning: warnInfo.map(w => w.text).join(',')
    });
}
// === end auto-generated ===
