export const MODULE_NAME = 'Truth Social';
export const DOMAIN = 'truthsocial.com';

// Function to remove HTML tags using a DOM Parser
function removeHtmlTagsUsingDOMParser(htmlString) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlString, 'text/html');
    return doc.body.textContent || "";
}

export function capture(response, source_platform_url, source_url) {
    let domain = source_platform_url.split("/")[2].toLowerCase().replace(/^www\./, '');

    if (!["truthsocial.com"].includes(domain)) {
        return [];
    }

    let data;
    let items = [];

    try {
        data = JSON.parse(response);
    } catch (SyntaxError) {
        return [];
    }

    function processPost(post) {
        if (!post.account) return null;
        post.content = removeHtmlTagsUsingDOMParser(post.content || "");
        return post;
    }

    if ((source_url.includes('following') || source_url.includes('truths') || source_url.includes('groups')) && Array.isArray(data)) {
        items = data.map(post => processPost(post));
    }

    return items;
}

// === auto-generated by 4cat map_item sync — BLOCK REPLACED AUTOMATICALLY ===
// (regenerated from datasources/truth/search_truth.py)
export function map_item(item) {
    const errors = [];
    const postTime = new Date(item["created_at"]);
    const images = [];
    const videos = [];
    const videoThumbs = [];

    if (item.media_attachments) {
        for (const media of item.media_attachments) {
            const mtype = media.type;
            if (mtype === "image") {
                images.push(media.url);
            } else if (mtype === "video") {
                videos.push(media.url);
                videoThumbs.push(media.preview_url);
            } else if (mtype === "tv") {
                // Truth social TV channels – only a thumbnail is provided
                videoThumbs.push(media.url);
                // preview_url is a smaller thumb (ignored)
            } else {
                errors.push(`New media type: ${mtype}`);
            }
        }
    }

    const group = item.group ? item.group : {};

    let thread_id;
    if (item.quote_id != null) {
        thread_id = item.quote_id;
    } else if (item.in_reply_to != null) {
        let reply_to = item.in_reply_to;
        while (reply_to) {
            if (reply_to.in_reply_to != null) {
                reply_to = reply_to.in_reply_to;
            } else {
                thread_id = reply_to.id;
                break;
            }
        }
    } else {
        thread_id = item.id;
    }

    const mentions = (item.mentions ?? []).map(m => m.username);
    const hashtags = (item.tags ?? []).map(t => t.name);

    // Format timestamp as "YYYY-MM-DD HH:MM:SS" in UTC
    const pad = n => String(n).padStart(2, "0");
    const timestamp = `${postTime.getUTCFullYear()}-${pad(postTime.getUTCMonth() + 1)}-${pad(postTime.getUTCDate())} ${pad(postTime.getUTCHours())}:${pad(postTime.getUTCMinutes())}:${pad(postTime.getUTCSeconds())}`;

    const mapped_item = {
        collected_from_url: normalize_url_encoding(item.__import_meta?.source_platform_url ?? ""),
        id: item.id,
        created_at: item.created_at,
        body: item.content,
        url: item.url ?? null,
        reblogs_count: item.reblogs_count ?? 0,
        replies_count: item.replies_count ?? 0,

        account_id: item.account.id,
        account_username: item.account.username,
        account_display_name: item.account.display_name,
        account_avatar: item.account.avatar,
        account_verified: item.account.verified,
        account_followers: item.account.followers_count,
        account_following: item.account.following_count,

        mentions: mentions.join(","),
        hashtags: hashtags.join(","),

        images: images.join(","),
        video_thumbs: videoThumbs.join(","),
        video_urls: videos.join(","),

        group_id: group.id ?? null,
        group_display_name: group.display_name ?? null,
        group_avatar: group.avatar ?? null,
        group_note: group.note ?? null,
        group_members_count: group.members_count ?? 0,

        thread_id: thread_id,
        timestamp: timestamp
    };

    return new MappedItem(mapped_item, errors.join("; "));
}
// === end auto-generated ===
